<?php


namespace frontend\modules\fileManager\controllers;


use mihaildev\elfinder\Controller;

class TestController extends Controller
{
    public function actionManager()
    {
        return parent::actionManager(); // TODO: Change the autogenerated stub
    }
}