<?php


namespace frontend\modules\lk\controllers;


use common\repositories\NotFoundException;
use core\entities\User\TblStaff;
use yii\web\Controller;
use Yii;

class MainController extends Controller
{
    /**
     * @var TblStaff
     */
    protected $staff;

    public function beforeAction($action)
    {
        $this->staff = $this->findModel(Yii::$app->request->get('id'));
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     * @return TblStaff
     */
    private function findModel($id)
    {
        $user = TblStaff::find()->with('user')->where(['id' => $id])->one();
        if (!isset($user))
            throw new NotFoundException('Пользователь не найден');
        return $user;
    }
}