<?php


namespace frontend\modules\api\controllers;


use core\entities\Common\FileLog;
use yii\web\Controller;

class FilesController extends Controller
{
    private $post;
    private $path;

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $this->post = \Yii::$app->request->get();
        if(!empty($this->post['options']['path']))
            $this->path = $this->post['options']['path'];
        else
            $this->path = $this->post['options']['url'];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionOpen()
    {
        $file = FileLog::create('Open', $this->path);
        return $file->save();
    }

    public function actionRename()
    {
        $desc = '';
        foreach ($this->post['added'] as $file)
            $desc .= 'New Name: ' . $file['name'] . "\r\n";
        $file = FileLog::create('Rename', $desc);
        return $file->save();
    }

    public function actionDownload()
    {
        $name = '';
        foreach ($this->post['files'] as $file)
            $name .= 'Name: ' . $file['name'] . "\r\n";
        $file = FileLog::create('Download', $name);
        return $file->save();
    }

    public function actionAdd()
    {
        $name = '';
        foreach ($this->post['added'] as $file)
            $name .= 'Add: ' . $file['name'] . "\r\n";
        $file = FileLog::create('Add', $name);
        return $file->save();
    }

    public function actionUpload()
    {
        $name = '';
        foreach ($this->post['added'] as $file)
            $name .= 'Upload: ' . $file['url'] . "\r\n";
        $file = FileLog::create('Upload', $name);
        return $file->save();
    }

    public function actionRemove()
    {
        $name = '';
        foreach ($this->post['changed'] as $file)
            $name .= 'Remove: ' . $file['name'] . "\r\n";
        $file = FileLog::create('Remove', $name);
        return $file->save();
    }
}